### ISSUE TITLE
RFC2: time relative	to day/night cycle

### ISSUE THREAD

**Issue by cpommier** [MIAPPE/MIAPPE#22]
feedback from @Andrew7millar
The specific problem that I found is that the sampling time 
Sampling time | The date-time when the sample was collected / harvested | 2005-08-15T15:52:01+00:00 | xsd:dateTime
 
is not related to the day/night cycle:
Average length of the light period | Average length of the light period in h. | 16 | xsd:float
 
And likewise for the various ‘regime’ values.
 
Therefore we cannot tell how a particular clock time of sampling relates to the light-dark condition, temperature, humidity or CO2.
This is critical for any photoperiod-dependent, light- or clock-regulated processes.
In a growth chamber this might even be controlled arbitrarily, whereas with semi-natural lighting one could with some work derive the time of dawn using the date and the lat. and long. of the facility.
 
Can you capture the (maybe average) time of dawn, for example? That would be a good start.
 

-----

Actually, a better solution will be to include a timeseries of light level + temperature in the dataset, not a single measure like the time of ‘lights-on’.

**Comment by DanFaria** [comment]
I fully agree with you, Cyril.
This level of detail should be captured at the data level, through a time-series of light + temperature.
Alternatively, global parameters like average length of the light period can be provided as environment parameters.

**Comment by Andrew7Millar** [comment]
@DanFaria I disagree but I see that I may have confused the issue by my final comment above.
At risk of stating the obvious, in which case my apologies, two distinct situations are relevant here: growth chambers where the day/night cycles are identical, and fluctuating or natural conditions.

First: 
The standard already contains multiple 'regime' terms such as "Average length of the light period". 
A term like that can only have relevance to the data points, if the time of each data sample relative to this average light period is recorded. Hence my request. This is a common approach for growth chambers. 

Second:
An alternative is to have the environmental time-series in the data, which is highly desirable for any natural or semi-natural conditions. But in that situation the 'Average length of the light period' should be deprecated. 

If the durations of each light period are being estimated from a light data timeseries in order to derive the average length above, then the timestamps of data points after the start of the current light period can also be inserted, as in the First scenario.

**Comment by DanFaria** [comment]
@Andrew7Millar My apologies if I did not address all the intricacies of the issue. Please bear in mind that my background is knowledge management & bioinformatics, not plant science, so some stating of the "obvious" is indeed merited.

WRT to the issue, I should start by clarifying that MIAPPE already fully supports two alternative approaches for modelling environment variables: 

1) Variables that are constant or were only measured grossly (e.g., average throughout the experiment) should be modeled as environment parameters.

2) Variables that were measured throughout the experiment should be treated as data (observations) and the variable should be described under the "observed variable" section.

We want to keep both alternatives in order to cater to the most use cases possible, and thus cannot deprecate any of the environment parameters. However, bear in mind that none of them are mandatory, so you needn't report "average length of the light period" if you measured light intensity throughout the experiment.

Bear in mind also that the environment parameters are not assumed to be exhaustive (it would be impossible) and that users can provide additional parameters if none satisfy their needs. You are free to provide the "average time of dawn" if this is necessary to complement the sample collection time and if you didn't measure light intensity throughout the experiment. I think we can also consider adding "average time of dawn" explicitly to the list of environment parameters (though I have absolutely no say on the parameters in that list; that's for plant scientists to decide).

Thus, there are already provisions in MIAPPE for both of the situations you mentioned.
It is paramount that sample times be provided under a single standard, to enable interoperability, so
I think having "average time of dawn" as an environment parameter is the cleanest way to relate sample times to the light intensity if you don't have light intensity as data.
Do note that, for "observed variables" you are free to record observations under a relative time (e.g. time since dawn) as long as you describe this in the "time scale" field.

**Comment by Andrew7Millar** [comment]
the "average time of dawn" is a good suggestion, thank you!

**Comment by cpommier** [comment]
Interesting discussion, and thanks @DanFaria for the clarifications. 
In conclusion we can either add "average time of dawn" in the annex or stay as is.
@PapoutsoglouE this clarification might be worth being added to the paper or in the supplementary material.

**Comment by cpommier** [comment]
I propose to stay as is with v1.1 and to move this discussion to V2.
you can reopen if you want.
