### ISSUE TITLE
RFC2: IV Environment (Emphasis)

### ISSUE THREAD

**Issue by cpommier** [MIAPPE/MIAPPE#29]
The definition of Environment is proposed as 

Environment | An environmental parameters or experimental conditions that was kept constant throughout the study and did not change betweeen observation units or assays.
-- | --

Here, we still have to consider the difference between ‘action’ and ‘environmental condition’. 
-	As stated above, environmental parameter is not appropriate (modelling community). Air temperature, which changes with time (even in a growth chamber) cannot be an environmental parameter. Plot size is an attribute of the protocol
-	The statistical community often uses ‘environment’ for ‘experiment’ (e.g. ‘Karsruhe 2016’)
-	Even if the action does not differ between units, environmental conditions always change with time and space, even in a growth chamber

Suggestion :Delete “environment” and replace by “common cultural practices” that may include ‘root medium’, or “target air temperature” (which differs from measured air temperature, which is a variable that changes with position (in the field/greenhouse/growth chamber) and with time (e.g. with outside temperature or when the cooling efficiency varies). For instance

Experimental protocol : common cultural practices | Cultural practices that were common to all experimental treatments
-- | --
Cultural practice | Name of the practice | List e in attachment to main MIAPPE table.Examples: target air temperature in a growth chamber; rooting medium; medium composition; | Free text (see Appendix I)
Environment parameter value | Value of the practice | Value for each of the above.Examples: 22 °C; Ca: 5 mg/L | Free text

**Comment by DanFaria** [comment]
-If "parameter" is inappropriate, we can switch to "environment variable" instead.
-The goal of the "environment" section is to describe environmental and experimental conditions that were kept constant throughout the experiment, or otherwise were monitored only grossly (e.g., "average air temperature" for the whole study). It covers conditions, not actions (which are covered by the cultural practices section).
-Environment variables that varied and were measured through time should be recorded as observation variables, and their values should be recorded as data (observations).
-Yes, plot size is an experimental condition, not quite an environmental one, but the field clearly includes the former in addition to the latter.
-Our target audience is the plant science community; not the statistical community. "Environment" should have a clear and objective meaning for the former, which decreases the likelihood of errors when filling in MIAPPE. The latter will surely have no trouble interpreting what is meant with "environment" from the definitions.
-We should, of course, improve our definitions to make sure these points are clear.

**Comment by Anne-Francoise** [comment]
My proposition of compromise:

**Environment:** this section refers to experimental target conditions or parameters that were meant to be kept constant throughout the study and were considered as uniform across all the observation units of the study. 
We could also add to the definition: "If the variation of an environmental parameter (e.g. air temperature) is recorded then it becomes an observed variable and it is managed in the _ad hoc_ section."

I would keep the word "environment" and replace "parameter" by "target parameter". In the key/value description.

**Comment by hcwi** [comment]
As discussed in #26, we are in favour of keeping the two possibilities of describing environment:
- _Environmental parameter_ for contant (set or assumed stable) characteristics of the environment in the _Enviroment_ section
- _Environmental variable_ for variable (measured) characteristics of the environment, in the _Observed Variable_ section, accompanied by the measument method

**Comment by cpommier** [comment]
Agreed.
- Environmental parameter for contant (set or assumed stable) characteristics of the environment in the Enviroment section
- Environmental variable for variable (measured) characteristics of the environment, in the Observed Variable section, accompanied by the measument method

**Comment by cpommier** [comment]
Tightly linked with #26 , I should have recorded them together.
Most of the modification of #26 should adress this. I have update the example which were indeed confusing.
