### ISSUE TITLE
RFC2: DM41/DM50 – could BioSample be an option in these fields

### ISSUE THREAD

**Issue by cpommier** [MIAPPE/MIAPPE#32]
Eg at
https://www.ncbi.nlm.nih.gov/biosample/ ;  https://www.ebi.ac.uk/biosamples/ ;https://www.elixir-europe.org/documents/elixir-webinar-biosamples-and-plans-ga4gh-metadata-api-sept-2016
However, we then see Biosamples as DM81 : "External ID" in the "Observation Unit" example. Not sure why these are called External ID when could be Biosample. However, maybe this is to allow xref to any other repository apart from Biosample at eg EBI ?

**Comment by PapoutsoglouE** [comment]
Entries on Biosamples refer to individual plants or parts thereof (MIAPPE observation units/samples), as opposed to the passport/lineage of a plant used in a study (MIAPPE biological material).  
They do contain a description of the material used, but the concept they represent is different.  

So I don't think it would be a good idea, especially since it does not help understanding and might give the wrong impression to the audience.  

DM81 is indeed titled `External ID` to allow references to other repositories, in addition to Biosamples.

**Comment by hcwi** [comment]
Agree with Eliana. Identification of biological material (DM41) and its source (DM50) are only a part of characteristics of a sample being obseved (registered at Biosamples), along with its handling in the experiment.

**Comment by PapoutsoglouE** [comment]
I don't think there is any action to be done here, unless we want to explicitly state in the definition that Biosample IDs cannot be used in those fields (DM41, DM51). DM81 already mentions Biosamples in the definition too.
What do you think?

**Comment by cpommier** [comment]
Almost, we need to add some comments in DM-41 for clarification for the users. Something like : 
DM-41 add: "The material identification is different from a BiosampleID which corresponds to Observation Unit or Samples sections below".
DM-72 replace : "The EBI Biosamples repository is recommended." with "The EBI Biosamples repository can be used."

**Comment by cpommier** [comment]
Done
DM-41 add: "The material identification is different from a BiosampleID which corresponds to Observation Unit or Samples sections below".
DM-72 replace : "The EBI Biosamples repository is recommended." with "The EBI Biosamples repository can be used."
