### ISSUE TITLE
MIAPPE V1.1 :DM73

### ISSUE THREAD

**Issue by cpommier** [MIAPPE/MIAPPE#33]
I understand the constraints, but this compounding of information for multi-dimensions may a)lead to error; b)make subsequent pre-processing for statistical analysis heavy work;  we prefer the normalised form ‘design factor’, ‘rank’, ‘value’, which is how a statistician would intuitively express to carry out ANOVA.
Specifically: an example “[Latitude] +2.341; [row] 4 ; [X] 3; [Y] 6; [Xm] 35; [Ym] 65; [Block] 1; [Plot] 894” would need to be parsed to be of value to a statistician. However, I do realise that this is a checklist and not a database schema…

**Comment by DanFaria** [comment]
Each observation unit has an assigned value for each experimental factor, under the field "Observation Unit factor value", so for the purpose of statistical analysis, parsing this field should be unnecessary.

This field is merely for localization purposes, and we do want to support a wide range of commonly used location schemes, while not enforcing any specific one. For that, a key-value pair is the best option to keep the standard simple and accessible, even if it will require additional effort to parse.

**Comment by richardostler** [comment]
Isn't this better addressed by providing a shapefile (DM-29), or else provided in the dataset? We would normally include any information such as block numbers, treatment factor group etc for the observation unit in the dataset.

**Comment by cpommier** [comment]
Postponed to V2

**Comment by hcwi** [comment]
Another technical aspect of this issue is the square brackets enclosing the key in: `[key] value;` pair.
We have another key-value list in In DM-44 (_Infraspecific name_) and there the format is `key: value;`, whereas for identifiers in general we expect `resourceID:value`.
For consistency and thus the ease of parsing one approach should be used - the one based on separation by colon `:` seems most natural. 
@cpommier @DanFaria @PapoutsoglouE, please check this aspect within RFC2

**Comment by PapoutsoglouE** [comment]
Agree with @hcwi.

**Comment by cpommier** [comment]
Agreed, issue created and self assigned.

**Comment by erlefloch** [comment]
Current status in branch 1.2 is :

DM-73 | Spatial distribution | Type  and value of a spatial coordinate (georeference or relative) or level  of observation (plot 45, subblock 7, block 2) provided as a key-value  pair of the form type:value. Levels of observation must be consistent  with those listed in the Study section. | “latitude:+2.341, row:4, X:3, Y:6, Xm:35, Ym:65; block:1; plot:894” | Formatted text (Key:value) | 0+
-- | -- | -- | -- | -- | --

This issue seems to be already solved. Feel free to reopen if needed.
