### ISSUE TITLE
Some references of checklist are not effective

### ISSUE THREAD

**Issue by Zodiacxxy** [MIAPPE/MIAPPE#47]
Some references can't be visited. For example: http://www.biosharing.org/bsg-000078

**Comment by PapoutsoglouE** [comment]
Could you specify which file/line that example came from? Off the top of my head, I am not aware of any references to Biosharing.

I am aware that the Crop Ontology site occasionally has issues, and as a result some of the CO terms given as examples might suffer because of that (e.g. [CO_715](http://www.cropontology.org/ontology/CO_715/Crop%20Research)). Unfortunately, I don't know what can be done about this.

**Comment by Zodiacxxy** [comment]
Sorry, i forget to give the name of file. 
It is "https://github.com/MIAPPE/MIAPPE/blob/master/MIAPPE_Checklist-v1.0/MIAPPE.docx". The checklist of MIAPPE.

**Comment by PapoutsoglouE** [comment]
I see. You are looking at the previous version of MIAPPE (v1.0), which is still preserved on this site. The newer version is MIAPPE v1.1 and you can find it in the other folder ([here](https://github.com/MIAPPE/MIAPPE/tree/master/MIAPPE_Checklist-Data-Model-v1.1)) in different formats. There is also a submission template to help you formulate your own (meta)data according to MIAPPE.

If, for some reason, you specifically want to check out the reference you mentioned, you can find it at [https://fairsharing.org/bsg-s000518/](https://fairsharing.org/bsg-s000518/)  - note that BioSharing has changed to FairSharing. But I don't think that the links listed in the MIAPPE v1.0 document will be updated anymore, since we now have the newer MIAPPE v1.1.

**Comment by Zodiacxxy** [comment]
Thank you for answer. Now i find it. It is very useful for me. And i hope you have a nice day. (*^_^*)
