### ISSUE TITLE
Inconsistent replicate example

### ISSUE THREAD

**Issue by cpommier** [MIAPPE/MIAPPE#55]
Line 100: 
DM-73	Spatial distribution	Type and value of a spatial coordinate (georeference or relative) or level of observation (plot 45, subblock 7, block 2) provided as a key-value pair of the form type:value. Levels of observation must be consistent with those listed in the Study section.	"latitude:+2.341; row:4 ; X:3; Y:6; Xm:35; Ym:65; block:1; plot:894; replicate:1"	Formatted text (Key:value)
Replicate should be removed to be consistent with the definition of DM-71

**Comment by cpommier** [comment]
@PapoutsoglouE I propose to release once this one is done.

**Comment by PapoutsoglouE** [comment]
Currently, the spatial distribution can hold:
* observation levels (plant, block, etc), or
* spatial coordinates that are not necessarily observation levels (X, lat, etc)

"Replicate" does not fit either of these, so I agree that something should be changed.

I think that it may be worth discussing revising the definition instead of the example here. Replicate information, as far as I understand, is useful to have somewhere, and we established that it cannot be an observation level.

So maybe it we should consider adding a third category to account for replicates? Though I am not entirely sure how it should be described. I am thinking something like:
> Type and value of a spatial coordinate (georeference or relative), level of observation (plot 45, subblock 7, block 2), or other distribution information (e.g. replicate) provided as a key-value pair...

**Comment by DanFaria** [comment]
It is still unclear to me why we would need to declare replicates explicitly.
It seems to me that two observation units (at the same level) that have the same germplasm(s) and the same treatment(s) are experimental replicates by default. Or am I missing something?
Also, we already have a section for the experimental design that would in principle cover the replicates.

Finally, if you do think we need to capture replicate information explicitly, then the way we were doing it (e.g., plot 1; replicate: 1) doesn't seem all that intuitive or useful because it doesn't explicitly capture what this is a replicate of (meaning, we would have to go to the experimental design to figure it out, at which point we probably wouldn't need this field in the first place).

All things considered, my vote would be to simply remove replicate from the list of spatial coordinates at this stage.
If, at a later stage, we feel like capturing replicates explicitly is needed, then I would add a replicate field to the observation unit section where the value is a list of identifiers of other observation units of which the present one is a replicate of.

**Comment by PapoutsoglouE** [comment]
In this case then, what is the preferred workflow?
a) make change directly on the master branch
b) pull request from new branch
c) rebase existing branch v1.1.2 onto master and pull request from there

As a side note: 
1) can branches v1.1.1 and v1.1.2 be closed?
2) should we make a v1.1-dev branch for future use?

**Comment by cpommier** [comment]
> All things considered, my vote would be to simply remove replicate from the list of spatial coordinates at this stage.
> If, at a later stage, we feel like capturing replicates explicitly is needed, then I would add a replicate field to the observation unit section where the value is a list of identifiers of other observation units of which the present one is a replicate of.
--> Agreed to remove replicate

For the branch management aspect this is related to the change made in 1.1.2. So simply make that change in branch 1.1.2, then let's rebase into master.
We should also release this. I create an issue for that.

**Comment by PapoutsoglouE** [comment]
@cpommier I have made the change on this branch but I am unsure how to proceed.  
Can you take it from here? The pull request currently looks ugly because of the previous non-fast-forward merge to master.

**Comment by cpommier** [comment]
Handled in #60
